package com.smcapis.smcapis.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Builder;

import java.util.List;

@JsonIgnoreProperties(ignoreUnknown = true)
@Builder(toBuilder = true)
public record RespuestaLiquidacionDetalle(
    @JsonProperty("liquidacion_id") int liquidacionId,
    int anio,
    String mes,
    @JsonProperty("nombre_completo") String nombreCompleto,
    String rut,
    String codigo,
    String grado,
    String nivel,
    String titulo,
    String jornada,
    String proceso,
    String reparticion,
    String cheque,
    @JsonProperty("caja_previsional") String cajaPrevisional,
    @JsonProperty("insitucion_salud") String institucionSalud,
    String bienios,
    @JsonProperty("carga_familiar") int cargaFamiliar,
    List<ItemLiquidacion> detalle,
    @JsonProperty("total_haberes") int totalHaberes,
    @JsonProperty("total_descuentos") int totalDescuentos,
    @JsonProperty("total_tribuitable") int totalTributable,
    @JsonProperty("total_imp_previsional") int totalImpPrevisional,
    @JsonProperty("total_imp_salud") int totalImpSalud,
    @JsonProperty("sueldo_liquido") int sueldoLiquido,
    @JsonProperty("dias_trabajados") int diasTrabajados,
    @JsonProperty("cotiz_pactada_isapre") String cotizPactadaIsapre,
    @JsonProperty("porcentaje_imp") String porcentajeImp,
    @JsonProperty("fecha_antiguedad") String fechaAntiguedad,
    @JsonProperty("horasExtras") String horasExtras,
    @JsonProperty("incDL3551") String incDL3551,
    @JsonProperty("asigResponsab") String asigResponsab,
    @JsonProperty("asigFamiliar") String asigFamiliar,
    @JsonProperty("planSuplem") String planSuplem,
    @JsonProperty("aporteSegInvSob") String aporteSegInvSob,
    @JsonProperty("segCesantiaEmp") String segCesantiaEmp,
    @JsonProperty("asigCritica") String asigCritica,
    @JsonProperty("asigLey18717") String asigLey18717,
    @JsonProperty("asigDireccionSuper") String asigDireccionSuper,
    @JsonProperty("horasExtras50porc") String horasExtras50porc,
    @JsonProperty("gastosRepresenta") String gastosRepresenta,
    @JsonProperty("mutual") String mutual,
    @JsonProperty("fondoBonoLaboral") String fondoBonoLaboral,
    @JsonProperty("difHabRetroactivos") String difHabRetroactivos,
    @JsonProperty("montoImponible") String montoImponible,
    @JsonProperty("montoImpDeshaucio") String montoImpDeshaucio,
    @JsonProperty("ahVoluntario") String ahVoluntario,
    @JsonProperty("retJudicial") String retJudicial,
    @JsonProperty("ahorPrevVol") String ahorPrevVol,
    @JsonProperty("segCesantia") String segCesantia,
    @JsonProperty("hdiFidelidad") String hdiFidelidad,
    @JsonProperty("hdiConductores") String hdiConductores,
    @JsonProperty("anticArrCasaFiscal") String anticipoArriendoCasaFiscal,
    @JsonProperty("casasCorfo") String casasCorfo,
    @JsonProperty("bienestarMOP") String bienestarMOP,
    @JsonProperty("mutualSeguros") String mutualSeguros,
    @JsonProperty("aporteBienMi") String aporteBienestarMunicipal,
    @JsonProperty("prestBienMi") String prestamoBienestarMunicipal,
    @JsonProperty("coopeuch") String coopeuch,
    @JsonProperty("prestamosCoopeuch") String prestamosCoopeuch,
    @JsonProperty("asocProfesionalesGobReg") String asocProfesionalesGobiernoRegional,
    @JsonProperty("prestamoAraucana") String prestamoAraucana,
    @JsonProperty("hogardeCristo") String hogarDeCristo,
    @JsonProperty("segInvSobEmp") String seguroInvalidezSobrevivenciaEmpresa,
    @JsonProperty("ciaSeguroConfuturo") String ciaSeguroConfuturo,
    @JsonProperty("flgSportlife") String flgSportlife,
    @JsonProperty("seguroHogarAraucana") String seguroHogarAraucana,
    @JsonProperty("seguroVidaAraucana") String seguroVidaAraucana,
    @JsonProperty("apvAFPCapital") String apvAFPCapital,
    @JsonProperty("achs") String achs,
    @JsonProperty("atrasos") String atrasos,
    @JsonProperty("ret3porcPrestamoSoli") String retencion3PorcientoPrestamoSolidario,
    @JsonProperty("texto_horas_extras") String textoHorasExtras,
    @JsonProperty("sueldo_liquido_palabras") String sueldoLiquidoPalabras
) {
}
